raw_data_dir: [
  'data/midis/raw'
]

processed_data_dir: 'data/midis/processed'

instru2track: {
  'Drums': 1, 'Piano': 2, 'Guitar': 3, 'Bass': 4, 'Strings': 5, 'Lead': 6,
}
instru2program: {
  'Drums': 0, 'Piano': 0, 'Guitar': 25, 'Bass': 32, 'Strings': 48, 'Lead': 80
} # filter_track_info

step_per_bar: 32

min_n_pitches: 10
min_n_notes: 50
max_n_beats: 1000
min_n_beats: 16
max_cross_bar_rate: 0.15
max_samples_per_ds: -1

required_tracks:
  - Lead
  - Piano|Guitar